apiVersion: v2
name: mlops-api
description: Helm chart for Document Q&A MLOps API
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - mlops
  - api
  - llm
  - kubernetes

maintainers:
  - name: Atharva Shedge
    email: atharvashedge237@gmail.com

home: https://github.com/atharvashedge237/DevOps_Project
sources:
  - https://github.com/atharvashedge237/DevOps_Project

dependencies: []