keyVault:
  enabled: true
  createSecretProviderClass: true
  secretProviderClassName: azure-keyvault-provider
  keyVaultName: mlops-vault
  tenantID: "${TENANT}"
  mountEnabled: false
  syncToK8sSecret: true
  k8sSecretName: ""
secrets:
  - name: OPENAI_API_KEY
    keyVaultName: mlops-vault
    secretName: openai-api-key
